zebimax_gen:
    resource: "@ZebimaxGenBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
login_check:
    path: /login_check

logout:
    path: /logout